version: '3'

services:
  api:
    build: ./api
    env_file:
      - ./environment/api.env
    ports:
      - "3025:3025"
    environment:
      - PORT=3025
    command: node server.js
    depends_on:
      - mongo
    restart: always

  dashboard:
    restart: always
    build: ./client/dashboard
    env_file:
      - ./environment/dashboard.env
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    command: npm run dev
    depends_on:
      - api

  mongo:
    restart: always
    image: mongo
    env_file:
      - ./environment/mongodb.env
    volumes:
      - astro-mongo-storage:/data/db
    ports:
      - 27017:27017

volumes:
  astro-mongo-storage:
